// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYZrcySb-ourouaQsRxlVXb8Et1i6Xs8',
    appId: '1:49866951058:web:549ab8821f1b3f8740594b',
    messagingSenderId: '49866951058',
    projectId: 'dokanbakikhata',
    authDomain: 'dokanbakikhata.firebaseapp.com',
    storageBucket: 'dokanbakikhata.firebasestorage.app',
    measurementId: 'G-Q1881GH08D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBolKk4QYV9HjmLoCE1gwhG6iZWw-76djg',
    appId: '1:49866951058:android:0c332d0a5cfae52940594b',
    messagingSenderId: '49866951058',
    projectId: 'dokanbakikhata',
    storageBucket: 'dokanbakikhata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0-j4VswwYC5uBOgrGIVDLe32LDMT4mG0',
    appId: '1:49866951058:ios:820aa3f4528287b140594b',
    messagingSenderId: '49866951058',
    projectId: 'dokanbakikhata',
    storageBucket: 'dokanbakikhata.firebasestorage.app',
    iosClientId: '49866951058-jltnl8nau22ige6a9h3lsh90hnrdvmlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dokanBakiMobile',
  );
}
